version: "3"

services:
  postgres:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-monitor-sensors}
    ports:
      - 5432:5432
